services:
    wakapi-api:
        build: .
        init: true
        depends_on:
            - wakapi-db
        ports:
            - 3032:3000
        restart: unless-stopped
        env_file:
            - ./.env

    wakapi-db:
        image: postgres:17
        restart: unless-stopped
        ports:
            - 8243:5432
        env_file:
            - ./.env
        volumes:
            - ./test-data/pgsql:/var/lib/postgresql/data

networks:
    default:
        name: wakapi-network
        driver: bridge
